# Generated by Django 3.0.8 on 2020-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport Wear'), ('OW', 'Outer Wear')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='lebl',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'seconday'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
