# Generated by Django 3.0.8 on 2020-07-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200719_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lebl',
            new_name='label',
        ),
    ]
